### ISSUE TITLE
Plantage dans "Mes tickets" si pas de scanner code barre installé

### ISSUE THREAD

**Issue by fperinel** [fperinel/android-MixIt#19]
Plantage dans "Mes tickets" si pas de scanner code barre installé

**Comment by fperinel** [comment]
java.lang.IllegalStateException: Could not execute method of the activity
at android.view.View$1.onClick(View.java:2191)
at android.view.View.performClick(View.java:2532)
at android.view.View$PerformClick.run(View.java:9277)
at android.os.Handler.handleCallback(Handler.java:587)
at android.os.Handler.dispatchMessage(Handler.java:92)
at android.os.Looper.loop(Looper.java:143)
at android.app.ActivityThread.main(ActivityThread.java:4196)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at android.view.View$1.onClick(View.java:2186)
... 11 more
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=com.google.zxing.client.android.SCAN pkg=com.google.zxing.client.android (has extras) }
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1569)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1539)
at android.app.Activity.startActivityForResult(Activity.java:2901)
at com.level42.mixit.activities.TicketActivity.actionAddTicket(TicketActivity.java:206)
... 14 more
