### ISSUE TITLE
Plantage a l'obtention des favoris

### ISSUE THREAD

**Issue by fperinel** [fperinel/android-MixIt#25]
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:200)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
at java.lang.Thread.run(Thread.java:1019)
Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 40: http://www.mix-it.fr/api/members/srogier /favorites
at java.net.URI.create(URI.java:776)
at org.apache.http.client.methods.HttpGet.<init>(HttpGet.java:75)
at com.level42.mixit.webservices.impl.WebServices.getRequestGET(WebServices.java:374)
at com.level42.mixit.webservices.impl.WebServices.getFavorite(WebServices.java:353)
at com.level42.mixit.services.impl.TalkService.getFavoris(TalkService.java:184)
at com.level42.mixit.services.impl.TalkService.getFavorisById(TalkService.java:308)
at com.level42.mixit.services.impl.TalkService.hydrateTalkFavoris(TalkService.java:249)
at com.level42.mixit.services.impl.TalkService.getTalks(TalkService.java:140)
at com.level42.mixit.services.impl.PlanningService.getTalksForPlanning(PlanningService.java:43)
at com.level42.mixit.tasks.GetPlanningAsyncTask.doInBackground(GetPlanningAsyncTask.java:40)
at com.level42.mixit.tasks.GetPlanningAsyncTask.doInBackground(GetPlanningAsyncTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:185)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
... 4 more

**Comment by fperinel** [comment]
Lié à un login contenant un espace.
Ajout encodage du paramètre + remontée de l'info
